version: '3.8'

services:
  coinwatcher-bot:
    build: .
    container_name: coinwatcher-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./bot_usage.log:/app/bot_usage.log

    # Ports können freigegeben werden, wenn nötig
    # ports:
    #   - "8443:8443"
